# Generated by Django 2.2.3 on 2019-07-09 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Einsatzmittel', '0002_auto_20190709_1723'),
    ]

    operations = [

        migrations.AlterField(
            model_name='buero',
            name='buero',
            field=models.CharField(max_length=20),
        ),
        migrations.AddField(
            model_name='buero',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
    ]
