# Generated by Django 2.2.3 on 2019-07-11 16:57

from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('Einsatzmittel', '0003_auto_20190709_1724'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buero',
            name='buerotage',
            field=multiselectfield.db.fields.MultiSelectField(choices=[(None, 'Bitte Bürotage auswählen'), ('Mo,Di,Mi,Do', 'Montag, Dienstag, Mittwoch und Donnerstag'), ('Mo', 'Montag'), ('Di', 'Dienstag'), ('Mi', 'Mittwoch')], default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='bus',
            name='fahrtage',
            field=models.CharField(choices=[(None, 'Bitte Bus-Fahrtage auswählen'), ('Di,Do', 'Dienstag und Donnerstag'), ('Mi,Fr', 'Mittwoch und Freitag'), ('Mo', 'Montag'), ('Di', 'Dienstag'), ('Mi', 'Mittwoch')], default='Di,Do', max_length=20),
        ),
    ]
