# Generated by Django 2.2.3 on 2019-07-11 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Einsatzmittel', '0004_auto_20190711_1857'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buero',
            name='buerotage',
            field=models.CharField(choices=[(None, 'Bitte Bürotage auswählen'), ('Mo,Di,Mi,Do', 'Montag, Dienstag, Mittwoch und Donnerstag'), ('Mo', 'Montag'), ('Di', 'Dienstag'), ('Mi', 'Mittwoch')], default='', max_length=20),
        ),
    ]
