# Generated by Django 2.2.3 on 2019-07-13 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Einsatzmittel', '0005_auto_20190711_1904'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buero',
            name='buerotage',
            field=models.CharField(choices=[(None, 'Bitte Bürotage auswählen'), ('Mo,Di,Mi,Do', 'Montag, Dienstag, Mittwoch und Donnerstag')], default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='bus',
            name='fahrtage',
            field=models.CharField(choices=[(None, 'Bitte Bus-Fahrtage auswählen'), ('Di,Do', 'Dienstag und Donnerstag'), ('Mi,Fr', 'Mittwoch und Freitag')], default='Di,Do', max_length=20),
        ),
    ]
