# Generated by Django 2.2.2 on 2019-06-19 12:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Fahrerteam', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fahrer',
            name='team',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Bus.Bus'),
        ),
    ]
