# Generated by Django 2.2.2 on 2019-06-25 13:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Fahrerteam', '0002_auto_20190619_1432'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='fahrer',
            options={'verbose_name': 'Fahrer', 'verbose_name_plural': 'Fahrer'},
        ),
    ]
