# Generated by Django 2.2.3 on 2019-07-09 14:21

from django.db import migrations, models
import django.db.models.deletion
import smart_selects.db_fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Klienten', '0001_initial'),
        ('Einsatzmittel', '0001_initial'),
        ('Einsatztage', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tour',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uhrzeit', models.TimeField()),
                ('entfernung', models.CharField(blank=True, max_length=100, null=True)),
                ('ankunft', models.TimeField(blank=True, null=True)),
                ('bemerkung', models.TextField(blank=True, max_length=200, null=True)),
                ('updated_on', models.DateTimeField(auto_now=True, null=True)),
                ('abholklient', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='abholort', to='Klienten.Klienten')),
                ('bus', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Einsatzmittel.Bus')),
                ('datum', smart_selects.db_fields.GroupedForeignKey(group_field='team', on_delete=django.db.models.deletion.CASCADE, to='Einsatztage.Fahrtag')),
                ('klient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='klient', to='Klienten.Klienten')),
                ('zielklient', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='zielort', to='Klienten.Klienten')),
            ],
            options={
                'verbose_name': 'Tour',
                'verbose_name_plural': 'Touren',
            },
        ),
    ]
