# Generated by Django 2.2.2 on 2019-06-19 16:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Klienten', '0004_auto_20190619_1736'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tour',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Uhrzeit', models.TimeField()),
                ('abholhausnr', models.CharField(max_length=10, null=True)),
                ('zielhausnr', models.CharField(max_length=10, null=True)),
                ('bemerkung', models.CharField(blank=True, max_length=200, null=True)),
                ('updated_on', models.DateTimeField(auto_now=True, null=True)),
                ('abholort', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='abholort', to='Klienten.Orte')),
                ('abholstrasse', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='abholstrasse', to='Klienten.Strassen')),
                ('klient', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Klienten.Klienten')),
                ('zielort', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='zielort', to='Klienten.Orte')),
                ('zielstrasse', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='zielstrasse', to='Klienten.Strassen')),
            ],
        ),
    ]
