# Generated by Django 2.2.3 on 2019-07-23 12:34

from django.db import migrations, models
import django.db.models.deletion
import smart_selects.db_fields


class Migration(migrations.Migration):

    dependencies = [
        ('Klienten', '0008_auto_20190722_1627'),
        ('Tour', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tour',
            name='bus1',
            field=smart_selects.db_fields.ChainedForeignKey(auto_choose=True, blank=True, chained_field='klient', chained_model_field='bus', null=True, on_delete=django.db.models.deletion.CASCADE, to='Klienten.Klienten'),
        ),
        migrations.AlterField(
            model_name='tour',
            name='bus',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Einsatzmittel.Bus'),
        ),
    ]
