# Generated by Django 2.2.2 on 2019-06-19 16:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Tour', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tour',
            name='Uhrzeit',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='tour',
            name='abholort',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='abholort', to='Klienten.Orte'),
        ),
        migrations.AlterField(
            model_name='tour',
            name='abholstrasse',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='abholstrasse', to='Klienten.Strassen'),
        ),
        migrations.AlterField(
            model_name='tour',
            name='klient',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Klienten.Klienten'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='tour',
            name='zielort',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='zielort', to='Klienten.Orte'),
        ),
        migrations.AlterField(
            model_name='tour',
            name='zielstrasse',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='zielstrasse', to='Klienten.Strassen'),
        ),
    ]
