# Generated by Django 2.2.2 on 2019-06-19 16:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Tour', '0002_auto_20190619_1818'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tour',
            old_name='Uhrzeit',
            new_name='uhrzeit',
        ),
    ]
