# Generated by Django 2.2.3 on 2019-07-23 12:47

from django.db import migrations
import django.db.models.deletion
import smart_selects.db_fields


class Migration(migrations.Migration):

    dependencies = [
        ('Tour', '0003_auto_20190723_1443'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tour',
            name='bus1',
            field=smart_selects.db_fields.ChainedForeignKey(auto_choose=True, chained_field='klient', chained_model_field='hausnr', null=True, on_delete=django.db.models.deletion.CASCADE, to='Klienten.Klienten'),
        ),
    ]
