# Generated by Django 2.2.2 on 2019-06-19 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tour', '0003_auto_20190619_1841'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tour',
            name='abholhausnr',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='tour',
            name='zielhausnr',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
