# Generated by Django 2.2.2 on 2019-06-23 12:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Klienten', '0005_auto_20190623_1432'),
        ('Tour', '0005_tour_bus'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tour',
            name='abholhausnr',
        ),
        migrations.RemoveField(
            model_name='tour',
            name='abholort',
        ),
        migrations.RemoveField(
            model_name='tour',
            name='abholstrasse',
        ),
        migrations.RemoveField(
            model_name='tour',
            name='zielhausnr',
        ),
        migrations.RemoveField(
            model_name='tour',
            name='zielort',
        ),
        migrations.RemoveField(
            model_name='tour',
            name='zielstrasse',
        ),
        migrations.AddField(
            model_name='tour',
            name='abholklient',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='abholort', to='Klienten.Klienten'),
        ),
        migrations.AddField(
            model_name='tour',
            name='zielklient',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='zielort', to='Klienten.Klienten'),
        ),
        migrations.AlterField(
            model_name='tour',
            name='klient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='klient', to='Klienten.Klienten'),
        ),
    ]
