# Generated by Django 2.2.2 on 2019-06-25 13:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Tour', '0006_auto_20190623_1432'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tour',
            options={'verbose_name': 'Tour', 'verbose_name_plural': 'Touren'},
        ),
    ]
