# Generated by Django 2.2.3 on 2019-07-24 14:46

from django.db import migrations
import django.db.models.deletion
import smart_selects.db_fields


class Migration(migrations.Migration):

    dependencies = [
        ('Tour', '0006_auto_20190724_1637'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tour',
            name='bus',
        ),
        migrations.AlterField(
            model_name='tour',
            name='bus1',
            field=smart_selects.db_fields.ChainedForeignKey(chained_field='klient', chained_model_field='name', null=True, on_delete=django.db.models.deletion.CASCADE, to='Klienten.KlientenBus'),
        ),
    ]
