# Generated by Django 2.2.3 on 2019-07-24 14:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Tour', '0007_auto_20190724_1646'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tour',
            old_name='bus1',
            new_name='bus',
        ),
    ]
