# Generated by Django 2.2.2 on 2019-06-26 15:03

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Einsatztage', '0004_auto_20190626_1703'),
        ('Tour', '0007_auto_20190625_1552'),
    ]

    operations = [
        migrations.AddField(
            model_name='tour',
            name='datum',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Einsatztage.Einsatztag'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='tour',
            name='uhrzeit',
            field=models.TimeField(),
        ),
    ]
