# Generated by Django 2.2.3 on 2019-07-24 15:12

from django.db import migrations
import django.db.models.deletion
import smart_selects.db_fields


class Migration(migrations.Migration):

    dependencies = [
        ('Tour', '0008_auto_20190724_1647'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tour',
            name='bus',
            field=smart_selects.db_fields.ChainedForeignKey(chained_field='klient', chained_model_field='name', on_delete=django.db.models.deletion.CASCADE, to='Klienten.KlientenBus'),
        ),
        migrations.AlterField(
            model_name='tour',
            name='datum',
            field=smart_selects.db_fields.ChainedForeignKey(auto_choose=True, chained_field='bus', chained_model_field='team', on_delete=django.db.models.deletion.CASCADE, to='Einsatztage.Fahrtag'),
        ),
    ]
