# Generated by Django 2.2.2 on 2019-06-19 13:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Fahrerteam', '0002_auto_20190619_1432'),
        ('Bus', '0002_auto_20190619_1416'),
    ]

    operations = [
        migrations.CreateModel(
            name='Einsatztag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datum', models.DateField(blank=True)),
                ('zeit', models.CharField(choices=[(None, 'Bitte Tageszeit auswählen'), ('Vormittag', 'Vormittag'), ('Nachmittag', 'Nachmittag')], default='Vormittag', max_length=10)),
                ('feiertag', models.BooleanField(default=False)),
                ('updated_on', models.DateTimeField(auto_now=True, null=True)),
                ('fahrer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Fahrerteam.Fahrer')),
                ('team', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Bus.Bus')),
            ],
        ),
    ]
