# Generated by Django 2.2.3 on 2019-07-09 15:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Einsatztage', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='buerotag',
            options={'verbose_name': 'Bürotag', 'verbose_name_plural': 'Bürotage'},
        ),
    ]
