# Generated by Django 2.2.2 on 2019-06-25 13:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Einsatztage', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='einsatztag',
            options={'verbose_name': 'Einsatztag', 'verbose_name_plural': 'Einsatztage'},
        ),
    ]
