# Generated by Django 2.2.2 on 2019-06-26 14:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Fahrerteam', '0003_auto_20190625_1552'),
        ('Einsatztage', '0002_auto_20190625_1552'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='einsatztag',
            name='fahrer',
        ),
        migrations.RemoveField(
            model_name='einsatztag',
            name='zeit',
        ),
        migrations.AddField(
            model_name='einsatztag',
            name='fahrer_nachmittag',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='nachmittag', to='Fahrerteam.Fahrer'),
        ),
        migrations.AddField(
            model_name='einsatztag',
            name='fahrer_vormittag',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vormittag', to='Fahrerteam.Fahrer'),
        ),
    ]
