# Generated by Django 2.2.2 on 2019-06-26 15:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Einsatztage', '0003_auto_20190626_1625'),
    ]

    operations = [
        migrations.AlterField(
            model_name='einsatztag',
            name='fahrer_nachmittag',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='nachmittag', to='Fahrerteam.Fahrer'),
        ),
        migrations.AlterField(
            model_name='einsatztag',
            name='fahrer_vormittag',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vormittag', to='Fahrerteam.Fahrer'),
        ),
    ]
