# Generated by Django 2.2.3 on 2019-07-24 15:30

from django.db import migrations
import django.db.models.deletion
import smart_selects.db_fields


class Migration(migrations.Migration):

    dependencies = [
        ('Einsatztage', '0005_auto_20190724_1716'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fahrtag',
            name='fahrer_nachmittag',
            field=smart_selects.db_fields.ChainedForeignKey(blank=True, chained_field='team', chained_model_field='team', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='nachmittag', to='Team.Fahrer'),
        ),
        migrations.AlterField(
            model_name='fahrtag',
            name='fahrer_vormittag',
            field=smart_selects.db_fields.ChainedForeignKey(blank=True, chained_field='team', chained_model_field='team', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='vormittag', to='Team.Fahrer'),
        ),
    ]
