# Generated by Django 2.2.3 on 2019-07-24 15:35

from django.db import migrations
import django.db.models.deletion
import smart_selects.db_fields


class Migration(migrations.Migration):

    dependencies = [
        ('Einsatztage', '0006_auto_20190724_1730'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buerotag',
            name='mitarbeiter',
            field=smart_selects.db_fields.ChainedForeignKey(blank=True, chained_field='team', chained_model_field='team', null=True, on_delete=django.db.models.deletion.CASCADE, to='Team.Buerokraft'),
        ),
    ]
