# Generated by Django 2.2.2 on 2019-06-19 12:02

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bus',
            fields=[
                ('bus', models.IntegerField(default=1, primary_key=True, serialize=False)),
                ('fahrtage', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, choices=[(None, 'Bitte Bus-Fahrtage auswählen'), ('Mo', 'Montag'), ('Di', 'Dienstag'), ('Mi', 'Mittwoch'), ('Do', 'Donnerstag'), ('Fr', 'Freitag')], default='Mo', max_length=2), size=None)),
                ('updated_on', models.DateTimeField(auto_now=True, null=True)),
            ],
        ),
    ]
