# Generated by Django 2.2.2 on 2019-06-19 12:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Bus', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bus',
            old_name='bus',
            new_name='bus_id',
        ),
    ]
