# Generated by Django 2.2.2 on 2019-06-25 13:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Bus', '0002_auto_20190619_1416'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bus',
            options={'verbose_name': 'Bus', 'verbose_name_plural': 'Busse'},
        ),
    ]
