# Generated by Django 2.2.3 on 2019-07-09 14:21

from django.db import migrations, models
import django.db.models.deletion
import smart_selects.db_fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Einsatzmittel', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Orte',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ort', models.CharField(max_length=50)),
                ('bus', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Einsatzmittel.Bus')),
            ],
            options={
                'verbose_name': 'Ort',
                'verbose_name_plural': 'Orte',
            },
        ),
        migrations.CreateModel(
            name='Strassen',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('strasse', models.CharField(max_length=50)),
                ('ort', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Klienten.Orte')),
            ],
            options={
                'verbose_name': 'Strasse',
                'verbose_name_plural': 'Strassen',
            },
        ),
        migrations.CreateModel(
            name='Klienten',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('telefon', models.CharField(blank=True, max_length=30, null=True)),
                ('mobil', models.CharField(blank=True, max_length=30, null=True)),
                ('hausnr', models.CharField(max_length=10)),
                ('dsgvo', models.CharField(blank=True, choices=[(None, 'Bitte Status auswählen'), ('01', 'Neu'), ('02', 'Versandt'), ('03', 'Unterschrieben'), ('99', 'Nicht notwendig')], default='01', max_length=2)),
                ('bemerkung', models.CharField(blank=True, max_length=200, null=True)),
                ('updated_on', models.DateTimeField(auto_now=True, null=True)),
                ('ort', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Klienten.Orte')),
                ('strasse', smart_selects.db_fields.ChainedForeignKey(auto_choose=True, chained_field='ort', chained_model_field='ort', on_delete=django.db.models.deletion.CASCADE, to='Klienten.Strassen')),
            ],
            options={
                'verbose_name': 'Klient',
                'verbose_name_plural': 'Klienten',
            },
        ),
    ]
