# Generated by Django 2.2.2 on 2019-06-19 14:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Orte',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ort', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Strassen',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('strasse', models.CharField(max_length=50)),
                ('ort', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Klienten.Orte')),
            ],
        ),
        migrations.CreateModel(
            name='Klienten',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('telefon', models.CharField(max_length=30)),
                ('hausnr', models.CharField(max_length=10)),
                ('dsgvo', models.BooleanField(default=False)),
                ('bemerkung', models.CharField(max_length=200)),
                ('updated_on', models.DateTimeField(auto_now=True, null=True)),
                ('ort', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Klienten.Orte')),
                ('strasse', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Klienten.Strassen')),
            ],
        ),
    ]
