# Generated by Django 2.2.3 on 2019-07-21 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Klienten', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='KlientenBus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('telefon', models.CharField(blank=True, max_length=30, null=True)),
                ('mobil', models.CharField(blank=True, max_length=30, null=True)),
                ('hausnr', models.CharField(max_length=10)),
                ('dsgvo', models.CharField(blank=True, choices=[(None, 'Bitte Status auswählen'), ('01', 'Neu'), ('02', 'Versandt'), ('03', 'Unterschrieben'), ('99', 'Nicht notwendig')], default='01', max_length=2)),
                ('bemerkung', models.CharField(blank=True, max_length=200, null=True)),
                ('bus_id', models.IntegerField()),
            ],
            options={
                'db_table': 'Klienten_klienten_bus',
                'managed': False,
            },
        ),
    ]
