# Generated by Django 2.2.2 on 2019-06-19 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Klienten', '0002_auto_20190619_1718'),
    ]

    operations = [
        migrations.AlterField(
            model_name='klienten',
            name='bemerkung',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
