# Generated by Django 2.2.3 on 2019-07-21 13:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Klienten', '0003_auto_20190721_1458'),
    ]

    operations = [
        migrations.AlterField(
            model_name='klienten',
            name='bus_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Einsatzmittel.Bus'),
        ),
    ]
