# Generated by Django 2.2.2 on 2019-06-23 12:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Klienten', '0004_auto_20190619_1736'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='klienten',
            options={'verbose_name_plural': 'Klienten'},
        ),
        migrations.AlterModelOptions(
            name='orte',
            options={'verbose_name': 'Ort', 'verbose_name_plural': 'Orte'},
        ),
    ]
