# Generated by Django 2.2.3 on 2019-07-21 13:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Klienten', '0004_auto_20190721_1508'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='klienten',
            name='bus_id',
        ),
    ]
