# Generated by Django 2.2.3 on 2019-07-21 13:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Einsatzmittel', '0006_auto_20190713_1819'),
        ('Klienten', '0005_remove_klienten_bus_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='klienten',
            name='bus',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Einsatzmittel.Bus'),
        ),
    ]
