# Generated by Django 2.2.2 on 2019-06-25 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Klienten', '0005_auto_20190623_1432'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='klienten',
            options={'verbose_name': 'Klient', 'verbose_name_plural': 'Klienten'},
        ),
        migrations.AlterModelOptions(
            name='strassen',
            options={'verbose_name': 'Strasse', 'verbose_name_plural': 'Strassen'},
        ),
        migrations.RemoveField(
            model_name='klienten',
            name='dsgvo',
        ),
        migrations.RemoveField(
            model_name='klienten',
            name='email',
        ),
        migrations.AddField(
            model_name='klienten',
            name='mobil',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
