# Generated by Django 2.2.2 on 2019-06-25 15:17

from django.db import migrations
import django.db.models.deletion
import smart_selects.db_fields


class Migration(migrations.Migration):

    dependencies = [
        ('Klienten', '0006_auto_20190625_1549'),
    ]

    operations = [
        migrations.AlterField(
            model_name='strassen',
            name='ort',
            field=smart_selects.db_fields.ChainedForeignKey(auto_choose=True, chained_field='ort', chained_model_field='ort', default=2, on_delete=django.db.models.deletion.CASCADE, to='Klienten.Orte'),
            preserve_default=False,
        ),
    ]
