# Generated by Django 2.2.3 on 2019-07-22 14:22

from django.db import migrations
import django.db.models.deletion
import smart_selects.db_fields


class Migration(migrations.Migration):

    dependencies = [
        ('Klienten', '0006_klienten_bus'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='klienten',
            name='bus',
        ),
        migrations.RemoveField(
            model_name='klienten',
            name='strasse',
        ),
        migrations.AddField(
            model_name='klienten',
            name='busNr',
            field=smart_selects.db_fields.ChainedForeignKey(auto_choose=True, chained_field='ort', chained_model_field='ort', default=4, on_delete=django.db.models.deletion.CASCADE, related_name='busNr', to='Klienten.Orte'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='klienten',
            name='strassenname',
            field=smart_selects.db_fields.ChainedForeignKey(auto_choose=True, chained_field='ort', chained_model_field='ort', default=1, on_delete=django.db.models.deletion.CASCADE, related_name='strassenname', to='Klienten.Strassen'),
            preserve_default=False,
        ),
    ]
