# Generated by Django 2.2.2 on 2019-06-25 15:41

from django.db import migrations, models
import django.db.models.deletion
import smart_selects.db_fields


class Migration(migrations.Migration):

    dependencies = [
        ('Klienten', '0007_auto_20190625_1717'),
    ]

    operations = [
        migrations.AlterField(
            model_name='klienten',
            name='ort',
            field=smart_selects.db_fields.ChainedForeignKey(auto_choose=True, chained_field='ort', chained_model_field='ort', on_delete=django.db.models.deletion.CASCADE, to='Klienten.Orte'),
        ),
        migrations.AlterField(
            model_name='strassen',
            name='ort',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Klienten.Orte'),
        ),
    ]
