# Generated by Django 2.2.3 on 2019-07-22 14:27

from django.db import migrations, models
import django.db.models.deletion
import smart_selects.db_fields


class Migration(migrations.Migration):

    dependencies = [
        ('Einsatzmittel', '0006_auto_20190713_1819'),
        ('Klienten', '0007_auto_20190722_1622'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='klienten',
            name='busNr',
        ),
        migrations.RemoveField(
            model_name='klienten',
            name='strassenname',
        ),
        migrations.AddField(
            model_name='klienten',
            name='bus',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Einsatzmittel.Bus'),
        ),
        migrations.AddField(
            model_name='klienten',
            name='strasse',
            field=smart_selects.db_fields.ChainedForeignKey(auto_choose=True, chained_field='ort', chained_model_field='ort', default=1, on_delete=django.db.models.deletion.CASCADE, to='Klienten.Strassen'),
            preserve_default=False,
        ),
    ]
