# Generated by Django 2.2.3 on 2019-07-24 14:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Einsatzmittel', '0006_auto_20190713_1819'),
        ('Klienten', '0008_auto_20190722_1627'),
    ]

    operations = [
        migrations.CreateModel(
            name='KlientenBus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bus', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Einsatzmittel.Bus')),
                ('name', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Klienten.Klienten')),
            ],
        ),
    ]
