# Generated by Django 2.2.3 on 2019-07-24 14:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Klienten', '0009_klientenbus'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='klientenbus',
            options={'verbose_name': 'Bus', 'verbose_name_plural': 'Busse'},
        ),
    ]
