# Generated by Django 2.2.2 on 2019-06-26 14:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Bus', '0003_auto_20190625_1552'),
        ('Klienten', '0009_auto_20190625_1745'),
    ]

    operations = [
        migrations.AddField(
            model_name='orte',
            name='bus',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Bus.Bus'),
        ),
    ]
